---
sidebar: sidebar 
permalink: rp-start-setup.html 
keywords: bluexp, ransomware protection, aws, azure 
summary: BlueXPランサムウェア対策を使用するには、いくつかの手順を実行してセットアップします。 
---
= BlueXPランサムウェア対策のセットアップ
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: /media/


[role="lead"]
BlueXPランサムウェア対策を使用するには、いくつかの手順を実行してセットアップします。

作業を開始する前に、 link:rp-start-prerequisites.html["前提条件"] 環境の準備が整っていることを確認します。



== バックアップ先の準備

次のいずれかのバックアップ先を準備します。

* NetApp StorageGRID
* Amazon Web Services の
* Microsoft Azure


バックアップ先自体でオプションを設定したら、あとでBlueXPランサムウェア対策サービスでバックアップ先として設定します。



=== StorageGRIDをバックアップ先にするための準備

StorageGRIDをバックアップ先として使用する場合は、を参照してください。 https://docs.netapp.com/us-en/storagegrid-117/index.html["StorageGRID のドキュメント"^] を参照してくださいStorageGRID。



=== バックアップ先としてのAWSの準備

* AWSでアカウントをセットアップします。
* 設定 https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions.html["AWS権限"^] 実現します。


BlueXPでのAWSストレージの管理の詳細については、 https://docs.netapp.com/us-en/bluexp-setup-admin/task-viewing-amazon-s3.html["Amazon S3バケットを管理します"^]。



=== Azureをバックアップ先にするための準備

* Azureでアカウントをセットアップします。
* 設定 https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions.html["Azure権限"^] Azure の場合：


BlueXPでのAzureストレージの管理の詳細については、 https://docs.netapp.com/us-en/bluexp-blob-storage/task-view-azure-blob-storage.html["Azureストレージアカウントの管理"^]。



== BlueXPをセットアップします

次のステップでは、BlueXPとBlueXPランサムウェア対策サービスをセットアップします。

レビュー https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html["BlueXPの標準の要件"^]。



=== BlueXPでコネクタを作成します

このサービスを試用または使用するには、NetApp営業担当者にお問い合わせください。その後、BlueXPコネクタを使用すると、ランサムウェア対策サービスに適した機能が含まれます。

サービスを使用する前にBlueXPでコネクタを作成する方法については、該当するBlueXPのドキュメントを参照してください https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html["BlueXPコネクタの作成方法"^]。


NOTE: BlueXPコネクタが複数ある場合は、BlueXP UIに現在表示されているコネクタ以外のすべてのコネクタのデータがスキャンされます。このサービスは、このアカウントに関連付けられているすべてのワークスペースとすべてのコネクタを検出します。
