---
sidebar: sidebar 
permalink: rp-start-prerequisites.html 
keywords: what are bluexp ransomware protection requirements, bluexp ransomware protection, ransomware protection prerequisites 
summary: お客様の環境、ネットワークアクセス、ログイン、Webブラウザのサポート状況を確認して、BlueXPランサムウェア対策を開始しましょう。 
---
= BlueXPのランサムウェア対策の前提条件
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/get-started/


[role="lead"]
運用環境、ログイン、ネットワークアクセス、Webブラウザの準備状況を確認して、BlueXPランサムウェア対策を始めましょう。

BlueXPランサムウェア対策を使用するには、次の前提条件が必要です。

* バックアップターゲットとアクセス権限が設定されたNetApp StorageGRIDまたはAWS S3のアカウント
+
を参照してください https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions.html["AWS権限リスト"^] を参照してください。

* ONTAP 9.11.1以降
+
** クラスタカンリシヤONTAPノケンケン
** オンプレミスのONTAPインスタンスで有効にする、BlueXPランサムウェア対策で使用するNetApp自律型ランサムウェア対策のライセンス。使用しているONTAPのバージョンに応じて異なります。を参照してください https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["Autonomous Ransomware Protection Overview"^]。
+

NOTE: BlueXPランサムウェア対策の一般リリースには、プレビューリリースとは異なり、NetApp自律型ランサムウェア対策テクノロジのライセンスが含まれています。を参照してください https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["Autonomous Ransomware Protection Overview"^] を参照してください。

+
ライセンスの詳細については、を参照してください。 link:concept-ransomware-protection.html["BlueXPランサムウェア対策の詳細をご確認ください"]。



* BlueXPの場合：
+
** BlueXPでは、各Virtual Private Cloud（VPC）またはオンプレミスのリージョンごとにBlueXPコネクタを設定する必要があります。を参照してください https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html["コネクタを設定するためのBlueXPドキュメント"^]。
+

NOTE: BlueXPコネクタが複数ある場合は、BlueXP UIに現在表示されているコネクタ以外のすべてのコネクタのデータがスキャンされます。

** 作業環境でバックアップを有効にしたBlueXPのバックアップとリカバリサービス
** NetAppオンプレミスストレージを使用するBlueXPの作業環境（NASまたはCIFSプロトコルを使用）
** オンプレミスのONTAPクラスタに接続するアクティブなコネクタが少なくとも1つあるBlueXPアカウント。すべてのソース環境と作業環境が同じBlueXPアカウントに属している必要があります。
** リソースを検出するためのアカウント管理者権限を持つBlueXPユーザアカウント
** https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html["BlueXPの標準の要件"^]



