---
sidebar: sidebar 
permalink: rp-start-faq.html 
keywords: ransomware protection faq, ransomware protection frequently asked questions 
summary: この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。 
---
= BlueXPのランサムウェア対策に関するFAQ
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。



== にアクセスします

* BlueXPランサムウェア対策URLとは？*
URLの場合は、ブラウザで次のように入力します。 https://console.bluexp.netapp.com/["https://console.bluexp.netapp.com/"^] をクリックしてBlueXPコンソールにアクセスします。

* BlueXPランサムウェア対策を使用するにはライセンスが必要ですか？*

次のライセンスタイプを使用できます。

* 90日間の無償トライアルにサインアップしてください。
* まもなく、Amazon Web Services（AWS）Marketplaceで従量課金制（PAYGO）サブスクリプションを購入できるようになります。
* まもなく、お客様所有のライセンスを使用（BYOL）できるようになります。BYOLは、NetApp営業担当から入手するNetAppライセンスファイル（NLF）です。ライセンスのシリアル番号を使用して、BlueXPデジタルウォレットでBYOLをアクティブ化できます。


* BlueXPのランサムウェア対策を有効にするには、どうすればよいですか？*
BlueXPのランサムウェア対策を有効にする必要はありません。ランサムウェア対策オプションは、BlueXPの左側のナビゲーションで自動的に有効になります。

このサービスをお試しいただくには、サインアップするか、NetApp営業担当者にお問い合わせください。BlueXP Connectorを使用すると、サービスに適した機能が含まれます。

** BlueXPのランサムウェア対策は、標準モード、制限モード、プライベートモードで利用できますか。**
現時点では、BlueXPのランサムウェア対策は標準モードでのみ利用できます。今後もご期待ください。

すべてのBlueXPサービスにおけるこれらのモードの詳細については、を参照してください。 https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["BlueXPの導入モード"^]。

**アクセス権限はどのように処理されますか?**
サービスを開始してワークロードを検出できるのはアカウント管理者だけです（リソースの使用をコミットする必要があるため）。その後の対話は、任意の役割で行うことができます。

**どのデバイス解像度が最適ですか?**
BlueXPのランサムウェア対策で推奨されるデバイス解決方法は、1920 x 1080以上です。

**どのブラウザを使用すればよいですか?**
最新のブラウザは機能します。



== 他のサービスとのやり取り

* BlueXPのランサムウェア対策はNetApp ONTAPで行われた保護設定を認識していますか？*
はい。BlueXPのランサムウェア対策では、ONTAPで設定されたSnapshotスケジュールが検出されます。

* BlueXPランサムウェア対策を使用してポリシーを設定した場合、今後このサービスのみを変更する必要がありますか？*
BlueXPランサムウェア対策サービスからポリシーを変更することをお勧めします。



== ワークロード

**ワークロードの構成要素**
ワークロードには、単一のアプリケーションインスタンスで使用されるすべてのボリュームが含まれます。たとえば、ora3.host.comに導入されたOracle DBインスタンスのデータとログには、それぞれvol1とvol2を含めることができます。これらのボリュームを合わせて、Oracle DBインスタンスの特定のインスタンスのワークロードを構成します。

* BlueXPのランサムウェア対策では、ワークロードデータの優先順位をどのように設定しますか？*
データの優先順位は、作成されるSnapshotコピーとスケジュールされたバックアップによって決まります。

ワークロードの優先順位はSnapshotの頻度によって決まります。

link:rp-use-protect.html["ワークロードの優先順位または重要性"]。

**新しいボリュームが追加されましたが、まだ表示されていません**
新しいボリュームを環境に追加した場合は、もう一度検出を開始し、保護ポリシーを適用して新しいボリュームを保護します。

**ダッシュボードにすべてのワークロードが表示されない。何が間違っている可能性がありますか。**
現時点では、NFSボリュームとCIFSボリュームのみがサポートされています。iSCSIボリュームおよびサポートされないその他の構成は除外され、ダッシュボードには表示されません。



== 保護ポリシー

* BlueXPランサムウェアポリシーは他の種類のワークロードポリシーと共存していますか？*
現時点では、BlueXPのバックアップとリカバリ（Cloud Backup）でサポートされるバックアップポリシーはボリュームごとに1つです。そのため、BlueXPのバックアップとリカバリとBlueXPのランサムウェア対策は、バックアップポリシーを共有しています。

Snapshotコピーに制限はなく、各サービスとは別に追加できます。
