---
sidebar: sidebar 
permalink: rp-start-faq.html 
keywords: ransomware protection faq, ransomware protection frequently asked questions 
summary: この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。 
---
= BlueXPのランサムウェア対策に関するFAQ
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。



== 導入

* BlueXPランサムウェア対策を使用するにはライセンスが必要ですか？*

次のライセンスタイプを使用できます。

* 30日間の無償トライアルにサインアップしてください。
* Amazon Web Services（AWS）Marketplace、Google Cloud Marketplace、Microsoft Azure Marketplace（近日提供予定）で従量課金制（PAYGO）サブスクリプションを購入
* お客様所有のライセンスを使用（BYOL）：NetApp営業担当から入手するNetAppライセンスファイル（NLF）です。ライセンスのシリアル番号を使用して、BlueXPデジタルウォレットでBYOLをアクティブ化できます。


* BlueXPのランサムウェア対策を有効にするには、どうすればよいですか？*
BlueXPのランサムウェア対策を有効にする必要はありません。ランサムウェア対策オプションは、BlueXPの左側のナビゲーションで自動的に有効になります。

このサービスをお試しいただくには、サインアップするか、NetApp営業担当者にお問い合わせください。BlueXP Connectorを使用すると、サービスに適した機能が含まれます。

BlueXP  ランサムウェア対策を開始するには、最初のランディングページで[Start discovering workloads]をクリックします。

* BlueXP  ランサムウェア対策は、標準モード、制限モード、プライベートモードで利用できますか？*現時点では、BlueXPのランサムウェア対策は標準モードでのみ利用できます。今後もご期待ください。

すべてのBlueXPサービスにおけるこれらのモードの詳細については、を参照してください。 https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["BlueXPの導入モード"^]。



== にアクセスします

* BlueXPランサムウェア対策URLとは？*BlueXP  コンソールにアクセスするには、ブラウザで次のように入力します。 https://console.bluexp.netapp.com/["https://console.bluexp.netapp.com/ransomware-protection"^]

*アクセス権限はどのように処理されますか？*サービスを開始してワークロードを検出できるのは、組織の管理者だけです（これにはリソースの使用をコミットする必要があるため）。その後の対話は、任意の役割で行うことができます。

*どのデバイス解像度が最適ですか？*BlueXPのランサムウェア対策で推奨されるデバイス解決方法は、1920 x 1080以上です。

*どのブラウザを使用すればよいですか？*最新のブラウザは機能します。



== 他のサービスとのやり取り

* BlueXPのランサムウェア対策はNetApp ONTAPで行われた保護設定を認識していますか？*はい。BlueXP  ランサムウェア対策では、ONTAPで設定されたSnapshotスケジュールが検出されます。

* BlueXPランサムウェア対策を使用してポリシーを設定した場合、今後このサービスのみを変更する必要がありますか？*
BlueXPランサムウェア対策サービスからポリシーを変更することをお勧めします。

* BlueXP  ランサムウェア対策は、BlueXP  のバックアップ/リカバリおよびSnapCenterとどのように連携しますか？*

BlueXP  ランサムウェア対策では、次の製品とサービスを使用します。

* ファイル共有ワークロードのSnapshotポリシーとバックアップポリシーを検出して設定するためのBlueXP  バックアップとリカバリ
* SnapCenterまたはSnapCenter for VMware：アプリケーションとVMワークロードのスナップショットポリシーとバックアップポリシーを検出して設定します。


さらに、BlueXP  ランサムウェア対策では、BlueXP  のバックアップとリカバリとSnapCenter / SnapCenter for VMwareを使用して、ファイルとワークロードの整合性のあるリカバリを実行します。



== ワークロード

*ワークロードの構成要素*ワークロードとは、アプリケーション、VM、ファイル共有のいずれかです。ワークロードには、単一のアプリケーションインスタンスで使用されるすべてのボリュームが含まれます。たとえば、ora3.host.comに導入されたOracle DBインスタンスのデータとログには、それぞれvol1とvol2を含めることができます。これらのボリュームを合わせて、Oracle DBインスタンスの特定のインスタンスのワークロードを構成します。

* BlueXPのランサムウェア対策では、ワークロードデータの優先順位をどのように設定しますか？*データの優先順位は、作成されるSnapshotコピーとスケジュールされたバックアップによって決まります。

ワークロードの優先度（critical、standard、important）は、ワークロードに関連付けられた各ボリュームにすでに適用されているSnapshotの頻度によって決まります。

link:rp-use-protect.html["ワークロードの優先順位または重要性"]。

* BlueXP  ランサムウェア対策はどのようなワークロードをサポートしていますか？*

BlueXP  ランサムウェア対策では、Oracle、MySQL、ファイル共有、VM、VMデータストアのワークロードを特定できます。

さらに、お客様がSnapCenterまたはSnapCenter for VMwareを使用している場合、これらの製品でサポートされているすべてのワークロードがBlueXP  ランサムウェア対策で特定され、BlueXP  ランサムウェア対策でワークロードと整合性のある方法で保護およびリカバリできます。

*どのようにしてデータをワークロードに関連付けますか？*

BlueXP  ランサムウェア対策は、次の方法でデータをワークロードに関連付けます。

* BlueXP  ランサムウェア対策は、ボリュームとファイル拡張子を検出し、適切なワークロードに関連付けます。
* さらに、SnapCenterまたはSnapCenter for VMwareを使用していて、BlueXP  のバックアップとリカバリでワークロードを設定している場合は、BlueXP  ランサムウェア対策によってSnapCenterおよびSnapCenter for VMwareで管理されているワークロードとその関連ボリュームが検出されます。


*「保護された」ワークロードとは何ですか？*BlueXP  ランサムウェア対策では、一次検出ポリシーが有効になっているワークロードのステータスが「protected」と表示されます。現時点では、ワークロードに関連するすべてのボリュームでARPが有効になっています。

*「リスクにさらされている」ワークロードとは何ですか？*ワークロードでプライマリ検出ポリシーが有効になっていない場合は、バックアップポリシーとSnapshotポリシーが有効になっていても「リスク」になります。

*新しいボリュームが追加されたがまだ表示されない*環境に新しいボリュームを追加した場合は、再度検出を開始し、保護ポリシーを適用して新しいボリュームを保護します。

*ダッシュボードにすべてのワークロードが表示されない。何が間違っている可能性がありますか？*現時点では、NFSボリュームとCIFSボリュームのみがサポートされています。 iSCSIボリュームおよびサポートされないその他の構成は除外され、ダッシュボードには表示されません。



== 保護ポリシー

* BlueXPランサムウェアポリシーは他の種類のワークロードポリシーと共存していますか？*
現時点では、BlueXPのバックアップとリカバリ（Cloud Backup）でサポートされるバックアップポリシーはボリュームごとに1つです。そのため、BlueXPのバックアップとリカバリとBlueXPのランサムウェア対策は、バックアップポリシーを共有しています。

Snapshotコピーに制限はなく、各サービスとは別に追加できます。

*ランサムウェア対策戦略にはどのようなポリシーが必要ですか？*

ランサムウェア対策戦略では、次のポリシーが必要です。

* ランサムウェア検出ポリシー
* スナップショットポリシー


BlueXP  ランサムウェア対策戦略ではバックアップポリシーは必要ありません。

* BlueXPのランサムウェア対策はNetApp ONTAPで行われた保護設定を認識していますか？*

はい。BlueXP  ランサムウェア対策は、ONTAPで設定されたSnapshotスケジュールと、検出されたワークロードのすべてのボリュームでARPとFPolicyが有効になっているかどうかを検出します。ダッシュボードに最初に表示される情報は、他のNetAppソリューションおよび製品から集約されます。

* BlueXP  ランサムウェア対策は、BlueXP  のバックアップとリカバリとSnapCenterで作成されたポリシーを認識していますか？*

はい。BlueXP  Backup and RecoveryまたはSnapCenterでワークロードを管理している場合、それらの製品で管理されているポリシーはBlueXP  ランサムウェア対策に適用されます。

* BlueXP  のバックアップ/リカバリやSnapCenterから引き継がれたポリシーを変更できますか。*

いいえ、BlueXP  Backup and Recoveryで管理されているポリシーや、BlueXP  ランサムウェア対策内のSnapCenterを変更することはできません。これらのポリシーへの変更は、BlueXP  Backup and RecoveryまたはSnapCenterで管理します。

* ONTAP（ARP、FPolicy、スナップショットなどのSystem Managerですでに有効化されている）のポリシーが存在する場合、BlueXP  ランサムウェア対策で変更されていますか？*

いいえ。 BlueXP  ランサムウェア対策では、ONTAPから既存の検出ポリシー（ARP、FPolicy設定）は変更されません。

* BlueXP  ランサムウェア対策にサインアップした後、BlueXP  Backup and RecoveryまたはSnapCenterに新しいポリシーを追加するとどうなりますか？*

BlueXP  ランサムウェア対策は、BlueXP  のバックアップとリカバリまたはSnapCenterで作成された新しいポリシーをすべて認識します。

* ONTAPからポリシーを変更できますか？*

はい、BlueXP  ランサムウェア対策のONTAPからポリシーを変更できます。BlueXP  ランサムウェア対策で新しいポリシーを作成してワークロードに適用することもできます。この操作により、既存のONTAPポリシーがBlueXP  ランサムウェア対策で作成されたポリシーに置き換えられます。

*ポリシーを無効にできますか？*

System ManagerのUI、API、またはCLIを使用して、検出ポリシーでARPを無効にすることができます。

FPolicyポリシーとバックアップポリシーを含まない別のポリシーを適用することで、それらのポリシーを無効にすることができます。
