= SANワークロードのサポート
:allow-uri-read: 




=== SANワークロードのサポート

このリリースでは、BlueXP ransomware protectionに SAN ワークロードのサポートが追加されました。および CIFS ワークロードに加えて、SAN ワークロードも保護できるようになりました。

詳細については、を参照してください link:https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-prerequisites.html["BlueXPのランサムウェア対策の前提条件"]。



=== ワークロード保護の改善

このリリースでは、 SnapCenterやBlueXP backup and recoveryなどの他のNetAppツールのスナップショットおよびバックアップポリシーを使用するワークロードの設定プロセスが改善されました。以前のリリースでは、 BlueXP ransomware protectionは他のツールのポリシーを検出し、検出ポリシーの変更のみが可能でした。このリリースでは、スナップショットおよびバックアップポリシーをBlueXP ransomware protectionポリシーに置き換えたり、他のツールのポリシーを引き続き使用したりできるようになりました。

詳細については、を参照してください link:https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-protect.html["ワークロードを保護"]。



=== Eメール通知

BlueXP ransomware protectionが攻撃の可能性を検出すると、 BlueXP通知に通知が表示され、設定した電子メール アドレスに電子メールが送信されます。

電子メールには、重大度、影響を受けるワークロード、 BlueXP ransomware protectionの *アラート* タブのアラートへのリンクに関する情報が含まれます。

BlueXP ransomware protectionでセキュリティおよびイベント管理 (SIEM) システムを構成した場合、サービスはアラートの詳細を SIEM システムに送信します。

詳細については、を参照してください link:https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-alert.html["検出されたランサムウェアアラートを処理する"]。
