= 攻撃のシミュレーションと対応
:allow-uri-read: 




=== 攻撃のシミュレーションと対応

このリリースでは、ランサムウェア攻撃をシミュレートして、ランサムウェアアラートへの対応をテストします。アラート通知、対応、リカバリの各プロセスをテストすることで、ランサムウェア攻撃が実際に発生した場合に備えておくことができます。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-simulate.html["ランサムウェア攻撃への備えの訓練を実施"]。



=== 検出プロセスの機能拡張

このリリースでは、選択的な検出プロセスと再検出プロセスが強化されています。

* このリリースでは、以前に選択した作業環境に追加された新たに作成されたワークロードを検出できます。
* このリリースでは、_new_working environmentsを選択することもできます。この機能は、環境に追加される新しいワークロードを保護するのに役立ちます。
* 検出されたすべてのワークロードを選択する場合は、*[すべて選択]*オプションを使用して選択できます。
* これらの検出プロセスは、最初の検出プロセス中に実行することも、設定オプション内で実行することもできます。


詳細については、およびを https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-settings.html["[Settings]オプションを使用してフェターを設定します。"]参照して https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-discover.html["以前に選択した作業環境用に新しく作成されたワークロードを検出する"]ください。



=== 高い暗号化が検出されたときに生成されるアラート

このリリースでは、高いファイル拡張子が変更されていなくても、ワークロードで高い暗号化が検出されたときにアラートを表示できます。ONTAP Autonomous Ransomware Protection（ARP）AIを使用するこの機能は、ランサムウェア攻撃のリスクがあるワークロードを特定するのに役立ちます。この機能を使用して、影響を受けるファイルのリスト全体をダウンロードし、拡張子を変更するかどうかを指定します。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-alert.html["検出されたランサムウェアに関するアラートに対応"]。
