= ランディングページの更新
:allow-uri-read: 




=== ランディングページの更新

このリリースには、BlueXP ランサムウェア保護のランディング ページの更新が含まれており、無料トライアルの開始と検出が容易になります。



=== 準備訓練の最新情報

以前は、新しいサンプルワークロードへの攻撃をシミュレートすることで、ランサムウェア対策訓練を実行できました。この機能を使用すると、シミュレートされた攻撃を調査し、ワークロードを復旧できます。この機能を使用して、アラート通知、対応、復旧をテストできます。これらの訓練は、必要に応じて何度でも実行およびスケジュールできます。

このリリースでは、BlueXP ランサムウェア保護ダッシュボードの新しいボタンを使用して、テスト ワークロードでランサムウェア準備ドリルを実行できるようになりました。これにより、制御された環境内でランサムウェア攻撃のシミュレーション、その影響の調査、ワークロードの効率的な回復が容易になります。

NFS ワークロードに加えて、CIFS (SMB) ワークロードでも準備ドリルを実行できるようになりました。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-simulate.html["ランサムウェア攻撃への備えの訓練を実施"]。



=== BlueXP分類の更新を有効にする

BlueXP  ランサムウェア対策サービスでBlueXP  分類を使用する前に、BlueXP  分類を有効にしてデータをスキャンする必要があります。データを分類すると、セキュリティ リスクを増大させる可能性のある個人を特定できる情報 (PII) を見つけるのに役立ちます。

BlueXPランサムウェア保護機能から、ファイル共有ワークロードにBlueXP分類を展開できます。「プライバシーの露出」列で「露出を特定」オプションを選択してください。分類サービスを有効にしている場合は、このアクションによって露出が特定されます。有効でない場合は、このリリースではダイアログボックスにBlueXP分類を展開するオプションが表示されます。「展開」を選択すると、BlueXP分類サービスのランディングページに移動し、サービスを展開できます。W

詳細については、  https://docs.netapp.com/us-en/bluexp-classification/task-deploy-cloud-compliance.html["BlueXPの分類機能をクラウドに導入します"^] BlueXPランサムウェア保護内でサービスを利用するには、  https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-protect-classify.html["BlueXP  分類を使用して、個人を特定できる情報をスキャンします。"] 。
